apiVersion: apps/v1
kind: Deployment
metadata:
  name: wetext-accounts-deployment
  labels:
    app: wetext-accounts-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wetext-accounts-service
  template:
    metadata:
      labels:
        app: wetext-accounts-service
    spec:
      containers:
      - name: wetext-accounts
        image: daxnet/wetext-accounts
        ports:
        - containerPort: 9020
---
apiVersion: v1
kind: Service
metadata:
  name: wetext-accounts-service
spec:
  ports:
  - port: 9020
  selector:
    app: wetext-accounts-service
